services:
  - type: web
    name: mlbased-dataset-evaluation  # Choose a unique name
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 3 --bind 0.0.0.0:$PORT app:app  # See note below
    healthCheckPath: /health  # Optional, but recommended
    envVars:
      - key: PORT
        value: "10000"  
